const images = {
  charger: 'https://images.unsplash.com/photo-1557767382-97b28f5488e7?auto=format&fit=crop&w=1200&q=80',
  headset: 'https://images.unsplash.com/photo-1710265029735-434f63c672c4?auto=format&fit=crop&w=1200&q=80',
  car: 'https://images.unsplash.com/photo-1619463061549-e14e1de6c14f?auto=format&fit=crop&w=1200&q=80',
  office: 'https://images.unsplash.com/photo-1586745370973-343d1ba81ed2?auto=format&fit=crop&w=1200&q=80',
  controller: 'https://images.unsplash.com/photo-1519888225640-4e937ce64761?auto=format&fit=crop&w=1200&q=80',
  stand: 'https://images.unsplash.com/photo-1629317480826-910f729d1709?auto=format&fit=crop&w=1200&q=80',
};

export const DEMO_PRODUCTS = [
  {
    id: 'tel-001', sku: 'TZ-CHR-30W', barcode: '6192410000014', name: 'Chargeur rapide USB-C 30 W',
    category: 'Téléphonie', subcategory: 'Chargeurs', brand: 'Voltix', condition: 'Neuf',
    shortDescription: 'Charge compacte et sécurisée pour smartphones et tablettes.',
    description: 'Un chargeur USB-C Power Delivery compact, conçu pour la maison et les déplacements. Sa protection intégrée limite les surtensions et la surchauffe.',
    price: 69.9, discountPrice: 54.9, stock: 18, colors: ['Blanc', 'Noir'], sizes: [], otherVariants: ['Prise EU'],
    image: images.charger, images: [images.charger, images.office], tags: ['usb-c', 'charge rapide', 'voyage'], featured: true, active: true, createdAt: '2026-08-28', updatedAt: '2026-09-02',
  },
  {
    id: 'tel-002', sku: 'TZ-PWB-20K', barcode: '6192410000021', name: 'Batterie externe 20 000 mAh',
    category: 'Téléphonie', subcategory: 'Batteries externes', brand: 'Voltix', condition: 'Neuf',
    shortDescription: 'Grande autonomie avec double sortie USB et affichage du niveau.',
    description: 'Rechargez deux appareils simultanément grâce à une batterie externe endurante. L’indicateur numérique permet de connaître précisément l’énergie restante.',
    price: 119.9, discountPrice: 99.9, stock: 9, colors: ['Noir', 'Bleu nuit'], sizes: [], otherVariants: ['20 000 mAh'],
    image: images.charger, images: [images.charger, images.stand], tags: ['autonomie', 'usb-c', 'voyage'], featured: false, active: true, createdAt: '2026-09-01', updatedAt: '2026-09-01',
  },
  {
    id: 'tel-003', sku: 'TZ-CAB-2M', barcode: '6192410000038', name: 'Câble USB-C renforcé 2 m',
    category: 'Téléphonie', subcategory: 'Câbles', brand: 'LinkPro', condition: 'Neuf',
    shortDescription: 'Câble tressé longue durée compatible avec la charge rapide.',
    description: 'Sa gaine tressée et ses connecteurs renforcés résistent aux torsions du quotidien. Longueur confortable de deux mètres.',
    price: 29.5, discountPrice: 0, stock: 26, colors: ['Noir', 'Bleu'], sizes: ['2 m'], otherVariants: [],
    image: images.charger, images: [images.charger], tags: ['câble', 'usb-c', 'charge rapide'], featured: false, active: true, createdAt: '2026-08-22', updatedAt: '2026-08-30',
  },
  {
    id: 'gam-001', sku: 'TZ-HS-RGB7', barcode: '6192410000045', name: 'Casque gaming Pulse RGB',
    category: 'Gaming', subcategory: 'Casques', brand: 'NovaGear', condition: 'Neuf',
    shortDescription: 'Son immersif, micro flexible et coussinets confortables.',
    description: 'Le casque Pulse RGB offre un son précis et un micro omnidirectionnel pour les parties en équipe. Son arceau réglable convient aux longues sessions.',
    price: 149.9, discountPrice: 129.9, stock: 0, colors: ['Noir', 'Blanc'], sizes: [], otherVariants: ['Jack 3,5 mm', 'USB'],
    variants: [
      { id: 'gam-001-noir', color: 'Noir', size: '', sku: 'TZ-HS-RGB7-N', barcode: '6192410001042', price: 129.9, stock: 4, active: true },
      { id: 'gam-001-blanc', color: 'Blanc', size: '', sku: 'TZ-HS-RGB7-B', barcode: '6192410001059', price: 134.9, stock: 3, active: true },
    ],
    image: images.headset, images: [images.headset, images.controller], tags: ['audio', 'rgb', 'esport'], featured: true, active: true, createdAt: '2026-08-30', updatedAt: '2026-09-02',
  },
  {
    id: 'gam-002', sku: 'TZ-PAD-WL', barcode: '6192410000052', name: 'Manette sans fil Arena',
    category: 'Gaming', subcategory: 'Manettes', brand: 'NovaGear', condition: 'Neuf',
    shortDescription: 'Commandes réactives et connexion stable pour PC.',
    description: 'Une manette ergonomique avec vibrations, gâchettes progressives et batterie rechargeable. Connexion sans fil et mode USB inclus.',
    price: 139, discountPrice: 0, stock: 11, colors: ['Noir', 'Rouge'], sizes: [], otherVariants: ['Sans fil'],
    image: images.controller, images: [images.controller, images.headset], tags: ['manette', 'pc', 'sans fil'], featured: false, active: true, createdAt: '2026-08-24', updatedAt: '2026-08-29',
  },
  {
    id: 'gam-003', sku: 'TZ-MAT-XL', barcode: '6192410000069', name: 'Tapis gaming Control XL',
    category: 'Gaming', subcategory: 'Accessoires', brand: 'Arena', condition: 'Neuf',
    shortDescription: 'Surface précise et base antidérapante au format bureau.',
    description: 'Le format XL accueille clavier et souris. Les bords cousus et la base caoutchoutée garantissent stabilité et durabilité.',
    price: 49.9, discountPrice: 39.9, stock: 15, colors: ['Noir'], sizes: ['80 × 30 cm'], otherVariants: [],
    image: images.office, images: [images.office], tags: ['souris', 'bureau', 'esport'], featured: false, active: true, createdAt: '2026-09-02', updatedAt: '2026-09-02',
  },
  {
    id: 'aut-001', sku: 'TZ-CAR-MAG', barcode: '6192410000076', name: 'Support voiture magnétique',
    category: 'Automobile', subcategory: 'Supports', brand: 'DrivePro', condition: 'Neuf',
    shortDescription: 'Fixation stable sur grille d’aération et rotation à 360°.',
    description: 'Gardez votre téléphone visible sans gêner la conduite. L’aimant renforcé et l’articulation orientable assurent une position stable.',
    price: 44.9, discountPrice: 34.9, stock: 21, colors: ['Noir'], sizes: [], otherVariants: ['Grille d’aération'],
    image: images.car, images: [images.car, images.charger], tags: ['voiture', 'téléphone', 'voyage'], featured: true, active: true, createdAt: '2026-08-27', updatedAt: '2026-09-02',
  },
  {
    id: 'aut-002', sku: 'TZ-CAR-45W', barcode: '6192410000083', name: 'Chargeur voiture double port 45 W',
    category: 'Automobile', subcategory: 'Chargeurs auto', brand: 'DrivePro', condition: 'Neuf',
    shortDescription: 'USB-C et USB-A pour recharger deux appareils en route.',
    description: 'Un chargeur compact pour prise 12 V avec deux ports et protection contre la surchauffe. Compatible avec la charge rapide Power Delivery.',
    price: 59.9, discountPrice: 0, stock: 13, colors: ['Noir'], sizes: [], otherVariants: ['12–24 V'],
    image: images.charger, images: [images.charger, images.car], tags: ['voiture', 'charge rapide', 'usb-c'], featured: false, active: true, createdAt: '2026-08-19', updatedAt: '2026-08-31',
  },
  {
    id: 'aut-003', sku: 'TZ-CAM-FHD', barcode: '6192410000090', name: 'Caméra de bord Full HD',
    category: 'Automobile', subcategory: 'Caméras de bord', brand: 'RoadEye', condition: 'Neuf',
    shortDescription: 'Enregistrement 1080p, vision nocturne et détection de mouvement.',
    description: 'Filmez vos trajets avec un grand angle net de jour comme de nuit. L’enregistrement en boucle simplifie la gestion de la carte mémoire.',
    price: 189, discountPrice: 169, stock: 0, colors: ['Noir'], sizes: [], otherVariants: ['1080p'],
    image: images.car, images: [images.car], tags: ['sécurité', 'caméra', 'voiture'], featured: false, active: true, createdAt: '2026-08-12', updatedAt: '2026-09-01',
  },
  {
    id: 'bur-001', sku: 'TZ-KEY-WL', barcode: '6192410000106', name: 'Clavier et souris sans fil',
    category: 'Bureautique', subcategory: 'Claviers et souris', brand: 'OfficeOne', condition: 'Neuf',
    shortDescription: 'Ensemble silencieux avec récepteur USB unique.',
    description: 'Un duo fiable pour travailler confortablement. Les touches silencieuses, la souris ambidextre et le récepteur partagé libèrent le bureau.',
    price: 89.9, discountPrice: 74.9, stock: 10, colors: ['Noir', 'Blanc'], sizes: [], otherVariants: ['AZERTY'],
    image: images.office, images: [images.office, images.stand], tags: ['bureau', 'sans fil', 'ordinateur'], featured: true, active: true, createdAt: '2026-08-31', updatedAt: '2026-09-02',
  },
  {
    id: 'bur-002', sku: 'TZ-STAND-AL', barcode: '6192410000113', name: 'Support ordinateur portable en aluminium',
    category: 'Bureautique', subcategory: 'Supports PC', brand: 'OfficeOne', condition: 'Neuf',
    shortDescription: 'Hauteur réglable et ventilation naturelle du portable.',
    description: 'Améliorez votre posture avec un support stable et réglable. Sa structure ouverte favorise la circulation de l’air sous l’ordinateur.',
    price: 109.9, discountPrice: 0, stock: 8, colors: ['Argent', 'Noir'], sizes: ['11–17 pouces'], otherVariants: [],
    image: images.stand, images: [images.stand, images.office], tags: ['ergonomie', 'ordinateur', 'bureau'], featured: false, active: true, createdAt: '2026-09-02', updatedAt: '2026-09-02',
  },
  {
    id: 'bur-003', sku: 'TZ-HUB-7P', barcode: '6192410000120', name: 'Hub USB-C 7-en-1',
    category: 'Bureautique', subcategory: 'Connectique', brand: 'LinkPro', condition: 'Neuf',
    shortDescription: 'HDMI, USB, lecteur de cartes et charge via un seul port.',
    description: 'Transformez un port USB-C en poste de travail complet. Le boîtier aluminium réunit HDMI, USB 3.0, cartes SD et alimentation.',
    price: 129.9, discountPrice: 109.9, stock: 6, colors: ['Gris'], sizes: [], otherVariants: ['HDMI 4K'],
    image: images.stand, images: [images.stand, images.charger], tags: ['usb-c', 'ordinateur', 'connectique'], featured: false, active: true, createdAt: '2026-08-26', updatedAt: '2026-09-01',
  },
];
